'use strict';

var op = function(actions) {
  return function(p) {
    return { type: 'OP', ops: actions };
  };
};

var sgr = {
  '0': function(p) { return op( [ [ 'resetAttribute' ] ] )(); },
  '1': op( [ [ 'setAttribute', 'bold' ] ] ),
  '3': op( [ [ 'setAttribute', 'italic' ] ] ),
  '4': op( [ [ 'setAttribute', 'underline' ] ] ),
  '5': op( [ [ 'setAttribute', 'blink' ] ] ),
  '7': op( [ [ 'setAttribute', 'inverse' ] ] ),
  '8': op( [ [ 'setAttribute', 'hidden' ] ] ),
  '9': op( [ [ 'setAttribute', 'strike' ] ] ),
  '22': op( [ [ 'unsetAttribute', 'bold' ] ] ),
  '23': op( [ [ 'unsetAttribute', 'italic' ] ] ),
  '24': op( [ [ 'unsetAttribute', 'underline' ] ] ),
  '25': op( [ [ 'unsetAttribute', 'blink' ] ] ),
  '27': op( [ [ 'unsetAttribute', 'inverse' ] ] ),
  '30': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '31': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '32': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '33': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '34': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '35': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '36': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '37': function(p) { return op([ [ 'setFgColor', (+p.cmd) - 30 ] ])(); },
  '38': function(p) { return op([ [ 'setFgColor', (+p.args) ] ])(); },
  '39': op( [ [ 'resetFgColor' ] ] ),
  '40': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '41': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '42': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '43': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '44': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '45': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '46': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '47': function(p) { return op([ [ 'setBgColor', (+p.cmd) - 40 ] ])(); },
  '48': function(p) { return op([ [ 'setBgColor', (+p.args) ] ])(); },
  '49': op( [ [ 'resetBgColor' ] ] ),
  '51': op( [ [ 'ATTR', 'FRAME:BOX' ] ] ),
  '52': op( [ [ 'ATTR', 'FRAME:CIRCLE' ] ] ),
  '53': op( [ [ 'ATTR', 'OVERLINED' ] ] ),
  '90': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '91': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '92': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '93': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '94': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '95': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '96': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '97': function(p) { return op([ [ 'setFgColor', (+p.cmd - 90 + 8) ] ])(); },
  '100': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '101': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '102': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '103': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '104': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '105': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '106': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  '107': function(p) { return op([ [ 'setBgColor', (+p.cmd - 100 + 8) ] ])(); },
  'fg-256': function(p) { return op([ [ 'setFgColor', (+p.args[0]) ] ])(); },
  'bg-256': function(p) { return op([ [ 'setBgColor', (+p.args[0]) ] ])(); },
};

module.exports = sgr;
